import type { CalendarSourceType } from "../types/calendar-source.type";

export const CALENDAR_SOURCES: CalendarSourceType[] = [
  {
    icon: "👑",
    slug: "leaders",
    url: "https://raw.githubusercontent.com/omergulcicek/calendar/refs/heads/main/leaders.json",
    displayName: "Liderler",
    description: "Açık kaynak liderler takvimi",
    list: [
      "Mehmet Âkif Ersoy",
      "Necip Fazıl Kısakürek",
      "Sezai Karakoç",
      "Cahit Zarifoğlu",
      "Rasim Özdenören",
      "Kadir Mısıroğlu",
      "Said Nursî",
      "Abdülhakim Arvâsî",
      "İmam Gazâlî",
      "Mevlânâ Celaleddin Rumi",
      "İmam Rabbani",
      "Muhsin Yazıcıoğlu",
      "Aliya İzzetbegović",
      "Malcolm X",
      "Muhammad Ali",
      "Necmettin Erbakan",
      "Yavuz Sultan Selim (I. Selim)",
      "Kanuni Sultan Süleyman (I. Süleyman)",
      "Fatih Sultan Mehmed (II. Mehmed)",
      "II. Abdülhamid",
      "I. Murad (Murad-ı Hüdavendigâr)",
      "II. Murad",
      "II. Bayezid (Veli)",
      "III. Selim",
      "II. Mahmud",
      "Cemil Meriç",
      "İsmet Özel",
      "Mahmut Ustaosmanoğlu",
      "Yıldırım Bayezid (I. Bayezid)",
      "Yavuz Bülent Bâkiler",
    ],
  },
  {
    icon: "⚔️",
    slug: "battles",
    url: "https://raw.githubusercontent.com/omergulcicek/calendar/refs/heads/main/battles.json",
    displayName: "Savaşlar",
    description: "Açık kaynak savaşlar takvimi",
    list: [
      "Dandanakan Savaşı",
      "Pasinler Savaşı",
      "Malazgirt Meydan Muharebesi",
      "Harran Savaşı",
      "Koyunhisar (Bafeus) Savaşı",
      "Sırpsındığı Savaşı",
      "Çirmen Savaşı",
      "I. Kosova Savaşı",
      "Niğbolu Savaşı",
      "İstanbul’un Fethi",
      "Eflak Seferi",
      "Otlukbeli Savaşı",
      "Çaldıran Savaşı",
      "Mercidabık Savaşı",
      "Ridaniye Savaşı",
      "Belgrad Seferi",
      "Rodos'un Fethi",
      "Mohaç Meydan Muharebesi",
      "Preveze Deniz Savaşı",
      "Zigetvar Seferi",
      "II. Viyana Kuşatması",
      "Kırım Savaşı",
      "93 Harbi (1877–1878 Osmanlı-Rus Savaşı)",
      "Çanakkale Savaşları",
      "Sakarya Meydan Muharebesi",
      "Büyük Taarruz",
      "İzmir’in Kurtuluşu",
    ],
  },
  {
    icon: "🌿",
    slug: "nature",
    url: "https://raw.githubusercontent.com/omergulcicek/calendar/refs/heads/main/nature.json",
    displayName: "Doğa ve Gökyüzü",
    description: "Mevsimler, göktaşı yağmurları, gün dönümleri ve ritüeller",
    list: [
      "Cemre (Havaya)",
      "Cemre (Suya)",
      "Cemre (Toprağa)",
      "Nevruz (Bahar Ekinoksu)",
      "Hıdırellez",
      "İstanbul Lale Mevsimi",
      "Perseid Göktaşı Yağmuru (Zirve)",
      "Geminid Göktaşı Yağmuru (Zirve)",
      "Sakura (Japon Kirazı) Çiçeği",
      "Yaz Gün Dönümü (En Uzun Gün)",
      "Kış Gün Dönümü (En Uzun Gece)",
      "İlkbahar Yakını İlk Dolunay",
      "Tam Ay Tutulması",
      "Tam Ay Tutulması",
      "Tam Güneş Tutulması",
      "Tam Güneş Tutulması",
      "Tam Güneş Tutulması",
      "Tam Ay Tutulması",
      "Tam Ay Tutulması",
      "Parçalı Güneş Tutulması",
    ],
  },
  {
    icon: "🌙",
    slug: "spiritual",
    url: "https://raw.githubusercontent.com/omergulcicek/calendar/refs/heads/main/spiritual.json",
    displayName: "Manevi günler",
    description: "Kandiller, Ramazan/Kurban Bayramları, Hicri yılbaşı ve Aşure",
    list: [
      "Regaip Kandili",
      "Miraç Kandili",
      "Berat Kandili",
      "Ramazan Başlangıcı",
      "Kadir Gecesi",
      "Ramazan Bayramı Arefesi",
      "Ramazan Bayramı",
      "Kurban Bayramı Arefesi",
      "Kurban Bayramı",
      "Hicri Yılbaşı (1 Muharrem 1446)",
      "Aşure Günü (10 Muharrem 1446)",
      "Mevlid Kandili",
      "Üç Ayların Başlangıcı",
    ],
  },
];

export function findCalendarSourceBySlug(
  slug: string
): CalendarSourceType | undefined {
  return CALENDAR_SOURCES.find((c) => c.slug === slug);
}
